# Generated by Django 3.2.13 on 2022-06-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20220609_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='convidados',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='ingresso',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='ingresso',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='ingressotransfer',
            name='current_owner',
        ),
        migrations.RemoveField(
            model_name='ingressotransfer',
            name='ingresso',
        ),
        migrations.RemoveField(
            model_name='ingressotransfer',
            name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='socio',
        ),
        migrations.DeleteModel(
            name='Convidado',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Ingresso',
        ),
        migrations.DeleteModel(
            name='IngressoTransfer',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
