# Generated by Django 3.2.13 on 2022-07-21 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('store', '0001_initial'), ('store', '0002_alter_item_has_variations'), ('store', '0003_item_is_variation'), ('store', '0004_auto_20220605_1504'), ('store', '0005_alter_cart_user'), ('store', '0006_remove_cartitem_item'), ('store', '0007_cartitem_item'), ('store', '0008_alter_cartitem_item'), ('store', '0009_alter_cartitem_item'), ('store', '0010_auto_20220605_1610'), ('store', '0011_cart_checked_out'), ('store', '0012_auto_20220605_2257'), ('store', '0013_auto_20220609_1602'), ('store', '0014_item_max_per_member'), ('store', '0015_auto_20220619_1340'), ('store', '0016_alter_item_image'), ('store', '0017_item_membership_exclusive'), ('store', '0018_auto_20220629_1637')]

    dependencies = [
        ('bank', '0010_alter_payment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0015_rename_payment_method_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='bank.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('checked_out', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('membership_price', models.FloatField(blank=True, null=True)),
                ('staff_price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Proporção da imagem: 1:1', null=True, upload_to='store/images/items')),
                ('stock', models.IntegerField(default=0)),
                ('has_variations', models.BooleanField(default=False, help_text='Marque para que sejam criadas variações para este item.')),
                ('is_digital', models.BooleanField(default=True, help_text='Vendido online?')),
                ('is_analog', models.BooleanField(default=True, help_text='Vendido presencial?')),
                ('is_active', models.BooleanField(default=True)),
                ('ref_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.item')),
                ('is_variation', models.BooleanField(default=False, editable=False)),
                ('max_per_member', models.PositiveIntegerField(blank=True, help_text='Máximo de itens por Sócio', null=True)),
                ('disabled_payment_methods', models.ManyToManyField(blank=True, help_text='Pagamentos bloqueados.', to='bank.PaymentMethod')),
                ('membership_exclusive', models.BooleanField(default=False, help_text='Exclusivo para Sócios?')),
            ],
            options={
                'ordering': ['is_variation'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='store/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('checked_out', models.BooleanField(default=False)),
                ('ordered', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
