# Generated by Django 3.2.13 on 2022-07-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial_squashed_0018_auto_20220629_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_event',
            field=models.BooleanField(default=False, help_text='Is this item an event?'),
        ),
        migrations.AddField(
            model_name='item',
            name='max_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of items per user', null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('remaining_uses', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='store.cart')),
            ],
        ),
    ]
