# Generated by Django 3.2.13 on 2022-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_rename_payment_method_payment_method'),
        ('store', '0014_item_max_per_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['user__member__name']},
        ),
        migrations.AddField(
            model_name='item',
            name='disabled_payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Payment methods that will not be available for this item.', to='bank.PaymentMethod'),
        ),
    ]
