# Generated by Django 3.2.13 on 2022-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_rename_payment_method_payment_method'),
        ('store', '0017_item_membership_exclusive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='item',
            name='disabled_payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Pagamentos bloqueados.', to='bank.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='item',
            name='has_variations',
            field=models.BooleanField(default=False, help_text='Marque para que sejam criadas variações para este item.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Proporção da imagem: 1:1', null=True, upload_to='store/images/items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_analog',
            field=models.BooleanField(default=True, help_text='Vendido presencial?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_digital',
            field=models.BooleanField(default=True, help_text='Vendido online?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_per_member',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de itens por Sócio', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='membership_exclusive',
            field=models.BooleanField(default=False, help_text='Exclusivo para Sócios?'),
        ),
    ]
