# Generated by Django 3.2.13 on 2022-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'atividade', 'verbose_name_plural': 'atividades'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['title'], 'verbose_name': 'anexo', 'verbose_name_plural': 'anexos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_date'], 'verbose_name': 'programação', 'verbose_name_plural': 'programações'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('W', 'Aguardando'), ('C', 'Confirmado'), ('E', 'Encerrado')], default='W', max_length=1),
        ),
    ]
