# Generated by Django 3.2.13 on 2022-06-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_programacao_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='competidor'
        ),
        migrations.DeleteModel(
            name='modalidade'
        ),
        migrations.DeleteModel(
            name='programacao'
        )
    ]
