# Generated by Django 3.2.13 on 2022-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0002_alter_partnership_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnership',
            options={'verbose_name': 'parceria', 'verbose_name_plural': 'parcerias'},
        ),
        migrations.AlterField(
            model_name='partnership',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='socio_benefits',
            field=models.TextField(verbose_name='benefícios de sócios'),
        ),
    ]
