# Generated by Django 3.2.13 on 2022-06-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20220531_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': 'membro', 'verbose_name_plural': 'membros'},
        ),
    ]
